<?php
defined('ABSPATH') or die('No Script Kiddes');

if ( in_array( 'woocommerce/woocommerce.php', apply_filters( 'active_plugins', get_option( 'active_plugins' ) ) ) ) {

    function shipping(){
        if (! class_exists('WPME_Shipping')){

            class WPME_Shipping extends WC_Shipping_Method{

                public function __construct()
                {
                    $this->id = 'wpme_melhorenvio';
                    $this->method_title = __("Melhor Envio 2","wpme_melhorenvio");
                    $this->method_description = __("Várias transportadoras, descontos, coletas e rastreamentos","wpme_melhorenvio");

                    $this->init();

                    $this->enabled = isset( $this->settings['enabled'] ) ? $this->settings['enabled'] : 'yes';
                    $this->title = isset( $this->settings['title'] ) ? $this->settings['title'] : __( 'Melhor Envio', 'wpme_melhorenvio' );
                }

                function init() {
                    $this->init_form_fields();
                    $this->init_settings();

                    add_action( 'woocommerce_update_options_shipping_' . $this->id, array( $this, 'process_admin_options' ) );

                }

                public function calculate_shipping($package = array())
                {
                    parent::calculate_shipping($package); // TODO: Change the autogenerated stub

                    return 20;
                }
            }
        }
    }

    add_action( 'woocommerce_shipping_init', 'melhorEnvioShippingInit' );

    function wpme_add_shipping( $methods ) {
        $methods['WPME_Shipping'] = 'WPME_Shipping';
        return $methods;
    }

    add_filter('woocommerce_shipping_methods', 'wpme_add_shipping');


}

?>